### ISSUE TITLE
System.OutOfMemoryException Parsing Nested Directives

### ISSUE THREAD

**Issue by kaleb** [TylerBrinks/ExCSS#4]
Note: The title of this issue may be using incorrect terminology.

I get a `System.OutOfMemoryException` when parsing the following CSS:

``` css
@page {
    size: letter;

    @bottom-right {
        content: counter(page);
    }
}
```
