### ISSUE TITLE
calc(expr) incorrectly parsed

### ISSUE THREAD

**Issue by brbulic** [TylerBrinks/ExCSS#74]
Example CSS 

``` css
.step-header-brlje > ul.process-bar > li:not(:first-child):after {
  content: '';
  width: calc(100% - 16px);
  position: absolute;
  left: calc(-50% + 6px);
  top: 10px;
  border-top: 2px solid gray;
}
```

Result CSS: 

``` css
.step-header-brlje > ul.process-bar > li:not(:first-child):after {
    content: '';
    width: calc(100% = 16px);
    position: absolute;
    left: calc(-50% = 6px);
    top: 10px;
    border-top: 2px solid gray;
}
```

Obviously the calc expressions are being parsed wrongly (notice the equal signs instead of math operators).

Can you assist ?
